# docker-compose.yml
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: elkazajo/client-client:latest  # Добавлено имя образа
    ports:
      - "9090:80"
    depends_on:
      - server
    environment:
      - REACT_APP_SOCKET_URL=http://localhost:3001
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: elkazajo/client-server:latest  # Добавлено имя образа
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - LLM_API_URL=http://host.docker.internal:1134/api/generate
    volumes:
      - ./server/uploads:/app/server/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge