# docker-compose.yml
version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:80"  # Изменен на порт 9090 снаружи
    depends_on:
      - server
    environment:
      - REACT_APP_SOCKET_URL=http://localhost:3001
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - LLM_API_URL=http://host.docker.internal:11434/api/generate
      - UI_URL=http://localhost:9090  # Также обновлено на 9090
    volumes:
      - ./server/uploads:/app/server/uploads
    networks:
      - app-network

networks:
  app-network:
    driver: bridge