# docker-compose.yml
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    depends_on:
      - server
    environment:
      - REACT_APP_SOCKET_URL=http://localhost:3001
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - LLM_API_URL=http://localhost:11434/api/generate
      - ALLOWED_ORIGINS=http://localhost:9090,http://localhost:3000
    volumes:
      - ./server/uploads:/app/server/uploads
      - ./server/data:/app/server/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge